/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ContentCard: typeof import('./src/components/ContentCard/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButtonGroup: typeof import('./src/components/SearchButtonGroup/index.vue')['default']
    TablePage: typeof import('./src/components/TablePage/index.vue')['default']
    TinyActionMenu: typeof import('@opentiny/vue')['ActionMenu']
    TinyBreadcrumb: typeof import('@opentiny/vue')['Breadcrumb']
    TinyBreadcrumbItem: typeof import('@opentiny/vue')['BreadcrumbItem']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyCol: typeof import('@opentiny/vue')['Col']
    TinyContainer: typeof import('@opentiny/vue')['Container']
    TinyDivider: typeof import('@opentiny/vue')['Divider']
    TinyDropdown: (typeof import('@opentiny/vue'))['Dropdown']
    TinyDropdownItem: (typeof import('@opentiny/vue'))['DropdownItem']
    TinyDropdownMenu: (typeof import('@opentiny/vue'))['DropdownMenu']
    TinyForm: typeof import('@opentiny/vue')['Form']
    TinyFormItem: typeof import('@opentiny/vue')['FormItem']
    TinyGrid: typeof import('@opentiny/vue')['Grid']
    TinyGridColumn: typeof import('@opentiny/vue')['GridColumn']
    TinyImage: typeof import('@opentiny/vue')['Image']
    TinyInput: typeof import('@opentiny/vue')['Input']
    TinyPager: typeof import('@opentiny/vue')['Pager']
    TinyRow: typeof import('@opentiny/vue')['Row']
    TinyStatistic: typeof import('@opentiny/vue')['Statistic']
    TinySwitch: typeof import('@opentiny/vue')['Switch']
    TinyTabItem: typeof import('@opentiny/vue')['TabItem']
    TinyTabs: typeof import('@opentiny/vue')['Tabs']
    TinyTag: typeof import('@opentiny/vue')['Tag']
    TinyTreeMenu: typeof import('@opentiny/vue')['TreeMenu']
    TinyUserHead: typeof import('@opentiny/vue')['UserHead']
  }
}
