/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./src/components/AdminMenu/index.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList/index.vue')['default']
    ArticleListItem: typeof import('./src/components/ArticleListItem/index.vue')['default']
    ContentCard: typeof import('./src/components/ContentCard/index.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButtonGroup: typeof import('./src/components/SearchButtonGroup/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    UploadImage: typeof import('./src/components/UploadImage/index.vue')['default']
    UserCard: typeof import('./src/components/UserCard/index.vue')['default']
  }
}
