/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AdminMenu: typeof import('./src/components/AdminMenu/index.vue')['default']
    ArticleList: typeof import('./src/components/ArticleList/index.vue')['default']
    ArticleListItem: typeof import('./src/components/ArticleListItem/index.vue')['default']
    ContentCard: typeof import('./src/components/ContentCard/index.vue')['default']
    MenuItem: typeof import('./src/components/MenuItem/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchButtonGroup: typeof import('./src/components/SearchButtonGroup/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TablePage: typeof import('./src/components/TablePage/index.vue')['default']
    TinyActionMenu: typeof import('@opentiny/vue')['ActionMenu']
    TinyBreadcrumb: typeof import('@opentiny/vue')['Breadcrumb']
    TinyBreadcrumbItem: (typeof import('@opentiny/vue'))['BreadcrumbItem']
    TinyButton: typeof import('@opentiny/vue')['Button']
    TinyCard: typeof import('@opentiny/vue')['Card']
    TinyCol: typeof import('@opentiny/vue')['Col']
    TinyContainer: typeof import('@opentiny/vue')['Container']
    TinyDialogBox: typeof import('@opentiny/vue')['DialogBox']
    TinyDivider: (typeof import('@opentiny/vue'))['Divider']
    TinyDropdown: (typeof import('@opentiny/vue'))['Dropdown']
    TinyDropdownItem: (typeof import('@opentiny/vue'))['DropdownItem']
    TinyDropdownMenu: (typeof import('@opentiny/vue'))['DropdownMenu']
    TinyFileUpload: typeof import('@opentiny/vue')['FileUpload']
    TinyForm: typeof import('@opentiny/vue')['Form']
    TinyFormItem: typeof import('@opentiny/vue')['FormItem']
    TinyGrid: typeof import('@opentiny/vue')['Grid']
    TinyGridColumn: typeof import('@opentiny/vue')['GridColumn']
    TinyImage: typeof import('@opentiny/vue')['Image']
    TinyInput: typeof import('@opentiny/vue')['Input']
    TinyNavMenu: typeof import('@opentiny/vue')['NavMenu']
    TinyPager: typeof import('@opentiny/vue')['Pager']
    TinyRow: typeof import('@opentiny/vue')['Row']
    TinyStatistic: (typeof import('@opentiny/vue'))['Statistic']
    TinySwitch: typeof import('@opentiny/vue')['Switch']
    TinyTabItem: (typeof import('@opentiny/vue'))['TabItem']
    TinyTabs: (typeof import('@opentiny/vue'))['Tabs']
    TinyTag: typeof import('@opentiny/vue')['Tag']
    TinyTreeMenu: (typeof import('@opentiny/vue'))['TreeMenu']
    TinyUserHead: typeof import('@opentiny/vue')['UserHead']
    UploadImage: typeof import('./src/components/UploadImage/index.vue')['default']
  }
}
